### ISSUE TITLE
FATAL: exception not rethrown

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#1295]
Calling any function results in the above error.

```py
from phylanx import Phylanx

@Phylanx
def foo(n):
    return n

foo(1)
```

output:
```
FATAL: exception not rethrown
```

Environment: https://github.com/rtohid/docker-build/blob/NN/phylanx/Dockerfile
Build script: https://github.com/rtohid/scripts/blob/master/kubuntu/build/phylanx/phylanx.sh

**Comment by hkaiser** [comment]
This must be caused by some exception being thrown early in the load process. Could you try running in gdb to see where that exception is thrown?

**Comment by rtohid** [comment]
Thank you @hkaiser. It's a release build. I'll retry with debug- it may take some time to build.

**Comment by stevenrbrandt** [comment]
I'm running release, and this isn't happening to me.

**Comment by rtohid** [comment]
Tried running one of the regression tests:
```
gdb -ex r --args python3 /home/stellar/src/phylanx/tests/regressions/python/852_concatenate_list.py
```
and got:
```
GNU gdb (GDB) Fedora 10.1-2.fc33
.
.
.

Reading symbols from python3...
Reading symbols from .gnu_debugdata for /usr/bin/python3.9...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.9)
Starting program: /usr/bin/python3 /home/stellar/src/phylanx/tests/regressions/python/852_concatenate_list.py
warning: Error disabling address space randomization: Operation not permitted
warning: Could not trace the inferior process.
warning: ptrace: Operation not permitted
During startup program exited with code 127.
Missing separate debuginfos, use: dnf debuginfo-install python3-3.9.1-1.fc33.x86_64
```

@stevenrbrandt , any ideas what might be the problem?

**Comment by stevenrbrandt** [comment]
@rtohid As discussed, Python 3.9 might be your problem. Alternatively, is this a docker image by chance? If so, you need to run the container with privilege if you want to use gdb.

**Comment by rtohid** [comment]
@stevenrbrandt, thanks!

This is what I get running on **Ubuntu 20.04** with **python 3.8.5**:
```
┌─[stellar][4fedc14564db][±][master ✓][~/.../regressions/python]
└─▪  python3 --version
Python 3.8.5

┌─[stellar][4fedc14564db][±][master ✓][~/.../regressions/python]
└─▪  python3 852_concatenate_list.py 
Traceback (most recent call last):
  File "852_concatenate_list.py", line 30, in <module>
    def concatenate_eager(tensors, axis):
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/ast/transducer.py", line 227, in Phylanx
    return _PhylanxDecorator(__phylanx_arg)
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/ast/transducer.py", line 80, in __init__
    self.backend = self.backends_map[self.backend](f, python_ast, kwargs)
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/ast/physl.py", line 517, in __init__
    self._ensure_is_compiled()
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/ast/physl.py", line 457, in _ensure_is_compiled
    self._ensure_compiler_state()
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/ast/physl.py", line 367, in _ensure_compiler_state
    phylanx.execution_tree.global_compiler_state(
  File "/home/stellar/git/phylanx/build/python/build/lib.linux-x86_64-3.8/phylanx/execution_tree/__init__.py", line 49, in global_compiler_state
    _compiler_state = compiler_state(name, file_name)
TypeError: Object of type 'module' is not an instance of 'weakref'
FATAL: exception not rethrown
``` 

[Dockerfile](https://github.com/rtohid/docker-build/blob/master/phylanx/Dockerfile.ubuntu)
[Docker image](https://hub.docker.com/r/rtohid/phylanx):  phylanx:issue1295

`docker pull rtohid/phylanx:issue1295`

No success with gdb, still get the same error on both Ubuntu and Fedora.

**Comment by stevenrbrandt** [comment]
@rtohid that looks like the issue I just fixed with pybind11. The correct code should be on the distributed_performance branch.

**Comment by rtohid** [comment]
@stevenrbrandt, thanks, it resolves the above issue. Tests still fail though- same issue as the  failing tests in #1297:

```
┌─[stellar][de4d4cfda341][±][distributed-performance ?:1 ✗][~/.../regressions/python]
└─▪  python3 852_concatenate_list.py 
FATAL: exception not rethrown
```

**Comment by hkaiser** [comment]
> @stevenrbrandt, thanks, it resolves the above issue. Tests still fail though- same issue as the failing tests in #1297:
> 
> ```
> ┌─[stellar][de4d4cfda341][±][distributed-performance ?:1 ✗][~/.../regressions/python]
> └─▪  python3 852_concatenate_list.py 
> FATAL: exception not rethrown
> ```

Please run in gdb and try to catch the exception when it is thrown (gdb command ‘catch throw’) and give us the stack batrace when gdb stops (gdb command ‘bt’).

**Comment by stevenrbrandt** [comment]
@rtohid @hkaiser I attempted to build with Python 3.8.6 and discovered the same `exception not rethorwn` error. I don't understan why this is happening, but (1) it happens during shutdown and (2) it comes from the pthread library.

**Comment by hkaiser** [comment]
> @rtohid @hkaiser I attempted to build with Python 3.8.6 and discovered the same `exception not rethorwn` error. I don't understan why this is happening, but (1) it happens during shutdown and (2) it comes from the pthread library.

We need to understand what exception is thrown from where. The commands I listed above should help figuring that out.

**Comment by rtohid** [comment]
https://stackoverflow.com/a/46676907 solves the issue with using gdb in containers. 
Here's what is the output: https://gist.github.com/rtohid/a0aafa519d436e4666f8062866e0984e

I pushed the image, to reproduce:

```sh
docker pull rtohid/phylanx:issue1295
docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined rtohid/phylanx:issue1295 
```

**Comment by hkaiser** [comment]
@rtohid thanks for this! Could you repeat that experiment with the code from https://github.com/STEllAR-GROUP/phylanx/pull/1297?

**Comment by rtohid** [comment]
> @rtohid thanks for this! Could you repeat that experiment with the code from #1297?

@hkaiser Above results are from #1297 (**distributed_performance** branch)

**Comment by stevenrbrandt** [comment]
@rtohid I usually use `--privileged=true`

**Comment by rtohid** [comment]
@hkaiser here is the minimal example with the trace:
https://gist.github.com/rtohid/a0aafa519d436e4666f8062866e0984e#gistcomment-3594343

**OS:** Ubuntu 20.04
**Python:** 3.8.5
**Branch:** [distributed_performance](https://github.com/STEllAR-GROUP/phylanx/tree/distributed_performance)

**Comment by hkaiser** [comment]
@rtohid are you sure you're working with the latest version of #1297? I'm still seeing the `TypeError: Object of type 'module' is not an instance of 'weakref'` message in your logs, which should have been fixed by the PR.

**Comment by rtohid** [comment]
> 
> 
> @hkaiser here is the minimal example with the trace:
> https://gist.github.com/rtohid/a0aafa519d436e4666f8062866e0984e#gistcomment-3594343
> 
> **OS:** Ubuntu 20.04
> **Python:** 3.8.5
> **Branch:** [distributed_performance](https://github.com/STEllAR-GROUP/phylanx/tree/distributed_performance)

@hkaiser, It's before the latest update, the test passes now. Thank you!

**Comment by hkaiser** [comment]
This was caused by our Python bindings on Python versions >= 3.8 and has been fixed now (https://github.com/STEllAR-GROUP/phylanx/pull/1297).
